[thresholds]
min_humidity = 30.0
max_humidity = 95.0
min_temp = 62.0
max_temp = 86.0

[fan]
# Fan power as a percentage of the maximum power (100.0)
power = 75.0
# Schedule for the fan to turn on and off
schedule = [
    { time = "00:00", action = "On" },
    { time = "00:10", action = "Off" },
    { time = "02:00", action = "On" },
    { time = "02:10", action = "Off" },
    { time = "04:00", action = "On" },
    { time = "04:10", action = "Off" },
    { time = "06:00", action = "On" },
    { time = "06:10", action = "Off" },
    { time = "08:00", action = "On" },
    { time = "08:10", action = "Off" },
    { time = "10:00", action = "On" },
    { time = "10:10", action = "Off" },
    { time = "12:00", action = "On" },
    { time = "12:10", action = "Off" },
    { time = "14:00", action = "On" },
    { time = "14:10", action = "Off" },
    { time = "16:00", action = "On" },
    { time = "16:10", action = "Off" },
    { time = "18:00", action = "On" },
    { time = "18:10", action = "Off" },
    { time = "20:00", action = "On" },
    { time = "20:10", action = "Off" },
    { time = "22:00", action = "On" },
    { time = "22:10", action = "Off" },
]

[light]
# Light schedule
schedule = [
    { time = "06:00", action = "On" },
    { time = "11:00", action = "Off" },
    { time = "12:30", action = "On" },
    { time = "14:30", action = "Off" },
    { time = "19:00", action = "On" },
    { time = "23:00", action = "Off" },
]
